---

- name: Install Python pip
  yum:
    name: python2-pip
    state: latest
  become: true
  when: install_tools

- name: Upgrade Python pip
  pip: 
    name: pip 
    state: present
  become: true
